In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

sns.set()
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import preprocessing
# Graphics in SVG format are more sharp and legible
%config InlineBackend.figure_format = 'svg'
from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/My Drive"
!ls "/content/drive/My Drive/Colab Notebooks"


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
 Classroom  'Colab Notebooks'   Videos	 Папка	 проекти
'Copy of featuretools.ipynb'
'Copy of Untitled1 (1).ipynb'
'Copy of Untitled1.ipynb'
 Homework_1.ipynb
 Homework4.ipynb
 Homework5.ipynb
'hw_pandas (1).ipynb'
 hw_pandas.ipynb
'player_data (1).csv'
 player_data.csv
'Players (1).csv'
 Players.csv
'Seasons_Stats (1).csv'
 Seasons_Stats.csv
'topic2_practice_visual_titanic_solution (1).ipynb'
 topic2_practice_visual_titanic_solution.ipynb
 Untitled0.ipynb
 Untitled2.ipynb
 winequality-red.csv
 winequality-white.csv


In [ ]:
data_red = pd.read_csv('/content/drive/My Drive/Colab Notebooks/winequality-red.csv', delimiter=';')
data_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [ ]:
data_red.describe(include="all")

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [ ]:
data_red.info()
data_red.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


(1599, 12)

In [ ]:
data_white = pd.read_csv('/content/drive/My Drive/Colab Notebooks/winequality-white.csv', delimiter=';')
data_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [ ]:
data_white.describe(include="all")

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [ ]:
data_white.info()
data_white.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


(4898, 12)

concat two datasets


In [ ]:
result = pd.concat([data_red, data_white])
result.head()


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [ ]:
result.shape

(6497, 12)

новая фича, смотрим сколько в винах всего химических примисей(соединяем количество хлоридов, диоксида серы общий, сульфаты)

In [ ]:
result['chemical impurities'] = result['total sulfur dioxide']+result['chlorides']+result['sulphates']
print (result['chemical impurities'])



0        34.636
1        67.778
2        54.742
3        60.655
4        34.636
         ...   
4893     92.539
4894    168.507
4895    111.501
4896    110.402
4897     98.340
Name: chemical impurities, Length: 6497, dtype: float64


In [ ]:
# Розділення датасету на навчальну та контрольну вибірки
X =  result.values[:, 0:10]
print(X)
Y =  result.values[:, 11]
print(Y)
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
X_train, X_validation, Y_train, Y_validation = train_test_split(X_scaled, Y, test_size=0.20, random_state=1)
X_train

[[7.4     0.7     0.      ... 0.9978  3.51    0.56   ]
 [7.8     0.88    0.      ... 0.9968  3.2     0.68   ]
 [7.8     0.76    0.04    ... 0.997   3.26    0.65   ]
 ...
 [6.5     0.24    0.19    ... 0.99254 2.99    0.46   ]
 [5.5     0.29    0.3     ... 0.98869 3.34    0.38   ]
 [6.      0.21    0.38    ... 0.98941 3.26    0.32   ]]
[5. 5. 5. ... 6. 7. 6.]


array([[-0.70607349, -1.27360683,  0.69760581, ..., -1.34624366,
        -0.55046457,  1.2684059 ],
       [ 0.14247327,  1.64213191, -2.12401256, ...,  0.92827074,
         1.62649313,  0.79795816],
       [-0.62893288, -0.36243847, -0.33469359, ...,  1.05500321,
        -0.48826578, -0.47897144],
       ...,
       [-0.16608919, -0.66616126,  0.69760581, ...,  0.16120576,
         1.75089072,  0.39471723],
       [-0.01180796,  1.76362102, -2.19283252, ...,  0.68481098,
         0.94230643,  0.32751041],
       [-1.16891718, -0.72690581, -0.6787934 , ...,  1.2851227 ,
         0.13372214, -0.34455779]])

In [ ]:
model = sm.OLS(Y_train, X_train)
results = model.fit()
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.006
Model:                            OLS   Adj. R-squared (uncentered):              0.004
Method:                 Least Squares   F-statistic:                              3.146
Date:                Fri, 14 Jul 2023   Prob (F-statistic):                    0.000505
Time:                        09:19:00   Log-Likelihood:                         -16575.
No. Observations:                5197   AIC:                                  3.317e+04
Df Residuals:                    5187   BIC:                                  3.324e+04
Df Model:                          10                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [ ]:
print("Parameters: ", results.params)
print("R2: ", results.rsquared)
print("Standard errors: ", results.bse)

Parameters:  [ 0.27991941 -0.17074849  0.15183791  0.53753766 -0.26453811 -0.21038184
 -0.00791226 -0.56275519  0.28788875  0.01580713]
R2:  0.010569200745095042
Standard errors:  [0.28900094 0.2191507  0.20482348 0.31361825 0.21853487 0.24426106
 0.26268874 0.35244262 0.21527323 0.19700874]


In [ ]:
model = LogisticRegression(solver='liblinear', random_state=1)
model.fit(X_train, Y_train)
predict = model.predict(X_validation)
score = model.score(X_validation, Y_validation)
print(score)
report = classification_report(Y_validation, predict)
print(report)

0.5338461538461539
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         4
         4.0       0.00      0.00      0.00        48
         5.0       0.58      0.59      0.58       435
         6.0       0.52      0.71      0.60       577
         7.0       0.46      0.13      0.21       203
         8.0       0.00      0.00      0.00        32
         9.0       0.00      0.00      0.00         1

    accuracy                           0.53      1300
   macro avg       0.22      0.20      0.20      1300
weighted avg       0.49      0.53      0.49      1300



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
cm = confusion_matrix(Y_validation, model.predict(X_validation))
cm

array([[  0,   1,   3,   0,   0,   0,   0],
       [  0,   0,  27,  21,   0,   0,   0],
       [  0,   0, 256, 177,   2,   0,   0],
       [  0,   0, 143, 411,  23,   0,   0],
       [  0,   0,  12, 164,  27,   0,   0],
       [  0,   0,   1,  25,   6,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0]])

In [ ]:
model = make_pipeline(StandardScaler(),
                    SGDRegressor(max_iter=1000, tol=1e-3))
model.fit(X_train, Y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdregressor', SGDRegressor())])

In [ ]:
predictions = model.predict(X_validation)
predictions

array([5.74730888, 5.37650929, 5.44688127, ..., 5.36354898, 5.21998704,
       6.33603435])

In [ ]:
print(accuracy_score(Y_validation, predictions.round()))
print(confusion_matrix(Y_validation, predictions.round(), normalize=None))
print(classification_report(Y_validation, predictions.round()))

0.5307692307692308
[[  0   0   3   1   0   0   0]
 [  0   0  19  29   0   0   0]
 [  0   0 196 233   6   0   0]
 [  0   0  95 452  30   0   0]
 [  0   0   9 152  42   0   0]
 [  0   0   0  26   6   0   0]
 [  0   0   0   0   1   0   0]]
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         4
         4.0       0.00      0.00      0.00        48
         5.0       0.61      0.45      0.52       435
         6.0       0.51      0.78      0.61       577
         7.0       0.49      0.21      0.29       203
         8.0       0.00      0.00      0.00        32
         9.0       0.00      0.00      0.00         1

    accuracy                           0.53      1300
   macro avg       0.23      0.21      0.20      1300
weighted avg       0.51      0.53      0.49      1300



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Смотрите хочу обучить модель предсказывать качество вина на имеющихся у нас данных, для этого беру в качестве Х - колонки датасета до 10 и в качестве У = колонку с показателями качества вина
Я масштабирую фичи в Х, разбиваю модельн а обучающую выборку и на валидационную.
 из того что я вижу я делаю вывод , что модель обучилась хорошо, поскольку R-squared  0.006, то есть среднеквадратичная ошибка стремится к нулю, однако построив предикт с помошью среднеквадратичнои регрессии я вижу accuracy_score = 0,53. Как я поимаю, что обучение данной модели в предикте дало  точность   правильных предсказаний всего 50%. Значит модель  предсказвает правильное качество  вина только на 50%, и это плохо. Что я сделала не так обучив модель, подскажите пожалуйста?  Или в какую сторону я должна смотреть, тоб обучить ее лучше?
