In [ ]:
# Import library
import numpy as np
from numpy import pi

Loading dataset Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [ ]:
content = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", dtype=str, encoding = None, delimiter=",", usecols=(0, 1, 2, 3))
data = content.astype(float)
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [ ]:

if data.ndim!=2:
  data = np.array([data])
data.ndim

2

Порахувати mean, median, standard deviation для 1-ї колонки

In [ ]:
result_mean_first_column = np.mean(data[:,0])
result_mean_first_column

5.843333333333334

In [ ]:
result_median_first_column = np.median(data[:,0])
result_median_first_column

5.8

In [ ]:
result_median_first_column = np.std(data[:,0])
result_median_first_column

0.8253012917851409

Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [ ]:
content = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", dtype=str, encoding = None, delimiter=",", usecols=(0, 1, 2, 3))
data = content.astype(float)
ii = np.random.choice(len(data), 20, replace=False)
j=0
for i in ii:
    data[i,j] = np.nan
    if(j<3):
      j=j+1
    else:
      j=j-1
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, nan],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, nan, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, nan],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Знайти позиції вставлених значень np.nan в 1-й колонці

In [ ]:
x = data[:,0]
x
np.argwhere(np.isnan(x))


array([[71]])

Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [ ]:
date_modify = data[(data[:, 2] > 1.5) & ( data[:, 2] < 5.0)]
date_modify


array([[5.4, 3.9, 1.7, 0.4],
       [4.8, 3.4, 1.6, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [4.8, 3.1, 1.6, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, nan],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [nan, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2

Замінити всі значення np.nan на 0

In [ ]:
data=np.nan_to_num(data)
data

# ####or use mask
# nan_mask = np.isnan(data)

# np.where(nan_mask, 0, data)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0. ],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 0. , 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0. ],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [ ]:
unique, counts = np.unique (data, return_counts= True )

print(np.asarray ((unique, counts)). T )

[[ 0.  20. ]
 [ 0.1  5. ]
 [ 0.2 26. ]
 [ 0.3  7. ]
 [ 0.4  7. ]
 [ 0.5  1. ]
 [ 0.6  1. ]
 [ 1.   8. ]
 [ 1.1  4. ]
 [ 1.2  7. ]
 [ 1.3 20. ]
 [ 1.4 19. ]
 [ 1.5 25. ]
 [ 1.6 10. ]
 [ 1.7  6. ]
 [ 1.8 12. ]
 [ 1.9  6. ]
 [ 2.   6. ]
 [ 2.1  5. ]
 [ 2.2  6. ]
 [ 2.3 11. ]
 [ 2.4  6. ]
 [ 2.5 11. ]
 [ 2.6  4. ]
 [ 2.7  9. ]
 [ 2.8 14. ]
 [ 2.9 10. ]
 [ 3.  27. ]
 [ 3.1 12. ]
 [ 3.2 13. ]
 [ 3.3  8. ]
 [ 3.4 12. ]
 [ 3.5  8. ]
 [ 3.6  3. ]
 [ 3.7  4. ]
 [ 3.8  7. ]
 [ 3.9  5. ]
 [ 4.   6. ]
 [ 4.1  4. ]
 [ 4.2  5. ]
 [ 4.3  2. ]
 [ 4.4  7. ]
 [ 4.5  9. ]
 [ 4.6  7. ]
 [ 4.7  6. ]
 [ 4.8  9. ]
 [ 4.9 10. ]
 [ 5.  14. ]
 [ 5.1 17. ]
 [ 5.2  5. ]
 [ 5.3  3. ]
 [ 5.4  8. ]
 [ 5.5 10. ]
 [ 5.6 12. ]
 [ 5.7 11. ]
 [ 5.8  9. ]
 [ 5.9  5. ]
 [ 6.   7. ]
 [ 6.1  8. ]
 [ 6.2  4. ]
 [ 6.3 10. ]
 [ 6.4  8. ]
 [ 6.5  5. ]
 [ 6.6  3. ]
 [ 6.7 10. ]
 [ 6.8  3. ]
 [ 6.9  5. ]
 [ 7.   1. ]
 [ 7.1  1. ]
 [ 7.2  3. ]
 [ 7.3  1. ]
 [ 7.4  1. ]
 [ 7.6  1. ]
 [ 7.7  4. ]
 [ 7.9  1. ]]


Розбити масив по горизонталі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [ ]:
data

arr1, arr2 = np.vsplit(data, 2)
arr2

array([[6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 0. ],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 0. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 0. , 1.8],
       [7.2, 3

Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [ ]:
result_arr1 = np.sort(arr1, axis=0)
result_arr1

array([[0. , 2. , 0. , 0. ],
       [4.3, 2.2, 0. , 0. ],
       [4.4, 2.2, 0. , 0. ],
       [4.4, 2.3, 0. , 0. ],
       [4.4, 2.3, 0. , 0.1],
       [4.5, 2.4, 1. , 0.1],
       [4.6, 2.5, 1.1, 0.1],
       [4.6, 2.5, 1.2, 0.1],
       [4.6, 2.7, 1.2, 0.1],
       [4.6, 2.7, 1.3, 0.2],
       [4.7, 2.8, 1.3, 0.2],
       [4.7, 2.8, 1.3, 0.2],
       [4.8, 2.8, 1.3, 0.2],
       [4.8, 2.8, 1.3, 0.2],
       [4.8, 2.9, 1.3, 0.2],
       [4.8, 2.9, 1.3, 0.2],
       [4.8, 2.9, 1.4, 0.2],
       [4.9, 2.9, 1.4, 0.2],
       [4.9, 2.9, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3.1, 1.4, 0.2],
       [5. , 3.1, 1.5, 0.2],
       [5. , 3.1, 1.5, 0.2],
       [5. , 3.1, 1.5, 0.2],
       [5.1, 3.1, 1.5, 0.2],
       [5.1, 3.1, 1.5, 0.2],
       [5.1, 3.1, 1.5, 0.2],
       [5.1, 3

In [ ]:
arr2 = np.sort(arr2, axis=0)
result_arr2 = arr2[::-1]
result_arr2

array([[7.9, 3.8, 6.9, 2.5],
       [7.7, 3.8, 6.7, 2.5],
       [7.7, 3.6, 6.7, 2.5],
       [7.7, 3.4, 6.6, 2.4],
       [7.7, 3.4, 6.4, 2.4],
       [7.6, 3.4, 6.3, 2.4],
       [7.4, 3.3, 6.1, 2.3],
       [7.3, 3.3, 6.1, 2.3],
       [7.2, 3.3, 6.1, 2.3],
       [7.2, 3.2, 6. , 2.3],
       [7.2, 3.2, 5.9, 2.3],
       [7.1, 3.2, 5.9, 2.3],
       [6.9, 3.2, 5.8, 2.3],
       [6.9, 3.2, 5.8, 2.2],
       [6.9, 3.1, 5.7, 2.2],
       [6.8, 3.1, 5.7, 2.2],
       [6.8, 3.1, 5.7, 2.1],
       [6.8, 3.1, 5.6, 2.1],
       [6.7, 3.1, 5.6, 2.1],
       [6.7, 3. , 5.6, 2.1],
       [6.7, 3. , 5.6, 2.1],
       [6.7, 3. , 5.6, 2. ],
       [6.7, 3. , 5.6, 2. ],
       [6.7, 3. , 5.5, 2. ],
       [6.7, 3. , 5.5, 2. ],
       [6.6, 3. , 5.5, 2. ],
       [6.5, 3. , 5.4, 1.9],
       [6.5, 3. , 5.4, 1.9],
       [6.5, 3. , 5.3, 1.9],
       [6.5, 3. , 5.3, 1.9],
       [6.4, 3. , 5.2, 1.8],
       [6.4, 3. , 5.1, 1.8],
       [6.4, 3. , 5.1, 1.8],
       [6.4, 3. , 5.1, 1.8],
       [6.4, 3

Зібрати обидва массиви в одне ціле

In [ ]:
new_sort_array = np.vstack([result_arr1, result_arr2])
new_sort_array

array([[0. , 2. , 0. , 0. ],
       [4.3, 2.2, 0. , 0. ],
       [4.4, 2.2, 0. , 0. ],
       [4.4, 2.3, 0. , 0. ],
       [4.4, 2.3, 0. , 0.1],
       [4.5, 2.4, 1. , 0.1],
       [4.6, 2.5, 1.1, 0.1],
       [4.6, 2.5, 1.2, 0.1],
       [4.6, 2.7, 1.2, 0.1],
       [4.6, 2.7, 1.3, 0.2],
       [4.7, 2.8, 1.3, 0.2],
       [4.7, 2.8, 1.3, 0.2],
       [4.8, 2.8, 1.3, 0.2],
       [4.8, 2.8, 1.3, 0.2],
       [4.8, 2.9, 1.3, 0.2],
       [4.8, 2.9, 1.3, 0.2],
       [4.8, 2.9, 1.4, 0.2],
       [4.9, 2.9, 1.4, 0.2],
       [4.9, 2.9, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3. , 1.4, 0.2],
       [5. , 3.1, 1.4, 0.2],
       [5. , 3.1, 1.5, 0.2],
       [5. , 3.1, 1.5, 0.2],
       [5. , 3.1, 1.5, 0.2],
       [5.1, 3.1, 1.5, 0.2],
       [5.1, 3.1, 1.5, 0.2],
       [5.1, 3.1, 1.5, 0.2],
       [5.1, 3

Знайти найбільш часто повторюване значення в массиві

In [ ]:
one_data = np.ravel(data)
values, counts = np.unique(one_data, return_counts=True)
position = np.where (counts== counts.max() )
result = values[position]
result

array([0.2])

Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [ ]:
def DevisionAndMultiply(arr):
  mean = np.mean(arr)
  prepared_data = np.where( arr >= mean , arr, arr*2)
  prepared_data = np.where( arr < mean, prepared_data, prepared_data/4)
  return prepared_data
DevisionAndMultiply(data)

array([[1.275, 0.875, 2.8  , 0.4  ],
       [1.225, 6.   , 2.8  , 0.4  ],
       [1.175, 6.4  , 2.6  , 0.4  ],
       [1.15 , 6.2  , 3.   , 0.4  ],
       [1.25 , 0.9  , 2.8  , 0.   ],
       [1.35 , 0.975, 3.4  , 0.8  ],
       [1.15 , 0.85 , 2.8  , 0.6  ],
       [1.25 , 0.85 , 3.   , 0.4  ],
       [1.1  , 5.8  , 2.8  , 0.4  ],
       [1.225, 6.2  , 3.   , 0.2  ],
       [1.35 , 0.925, 3.   , 0.4  ],
       [1.2  , 0.85 , 3.2  , 0.4  ],
       [1.2  , 6.   , 2.8  , 0.2  ],
       [1.075, 6.   , 2.2  , 0.2  ],
       [1.45 , 1.   , 2.4  , 0.4  ],
       [1.425, 1.1  , 3.   , 0.8  ],
       [1.35 , 0.975, 2.6  , 0.8  ],
       [1.275, 0.875, 2.8  , 0.6  ],
       [1.425, 0.95 , 3.4  , 0.6  ],
       [1.275, 0.95 , 3.   , 0.6  ],
       [1.35 , 0.85 , 3.4  , 0.4  ],
       [1.275, 0.925, 3.   , 0.8  ],
       [1.15 , 0.9  , 2.   , 0.4  ],
       [1.275, 6.6  , 3.4  , 1.   ],
       [1.2  , 0.85 , 3.8  , 0.4  ],
       [1.25 , 6.   , 3.2  , 0.4  ],
       [1.25 , 0.85 , 3.2  , 0.8  ],
 

Застосувати отриману функцію до 3-ї колонки


In [ ]:
third_column = data[:,2]
DevisionAndMultiply(third_column)


array([2.8  , 2.8  , 2.6  , 3.   , 2.8  , 3.4  , 2.8  , 3.   , 2.8  ,
       3.   , 3.   , 3.2  , 2.8  , 2.2  , 2.4  , 3.   , 2.6  , 2.8  ,
       3.4  , 3.   , 3.4  , 3.   , 2.   , 3.4  , 3.8  , 3.2  , 3.2  ,
       3.   , 2.8  , 0.   , 3.2  , 3.   , 3.   , 2.8  , 3.   , 2.4  ,
       2.6  , 3.   , 2.6  , 3.   , 2.6  , 2.6  , 2.6  , 3.2  , 3.8  ,
       2.8  , 3.2  , 2.8  , 3.   , 2.8  , 0.   , 1.125, 1.225, 1.   ,
       1.15 , 1.125, 1.175, 6.6  , 1.15 , 0.975, 0.875, 1.05 , 1.   ,
       1.175, 0.   , 0.   , 1.125, 1.025, 1.125, 0.975, 1.2  , 1.   ,
       1.225, 1.175, 0.   , 1.1  , 1.2  , 1.25 , 1.125, 0.875, 0.95 ,
       0.925, 0.975, 1.275, 1.125, 1.125, 1.175, 1.1  , 1.025, 1.   ,
       1.1  , 1.15 , 1.   , 6.6  , 1.05 , 1.05 , 1.05 , 1.075, 6.   ,
       1.025, 0.   , 1.275, 1.475, 1.4  , 1.45 , 1.65 , 1.125, 1.575,
       0.   , 1.525, 1.275, 1.325, 1.375, 1.25 , 1.275, 1.325, 1.375,
       1.675, 1.725, 1.25 , 1.425, 1.225, 1.675, 0.   , 1.425, 1.5  ,
       1.2  , 1.225,